plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ctofinder.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.ctofinder.app"
        minSdk 26
        targetSdk 35
        versionCode 7
        versionName "1.6"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
}
